version: '3.9'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_inertia
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - app-network
    command: bash -c "php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

networks:
  app-network:
    driver: bridge
